name = "borutouzumaki07-profile-counter"
main = "src/index.js"
compatibility_date = "2026-10-06"

[[durable_objects.bindings]]
name = "PROFILE_COUNTER"
class_name = "ProfileCounter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ProfileCounter"]
